services:
#    dev_sous_titre.example:
#        class: Dev\SousTitreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    traductionservice:
        class: Dev\SousTitreBundle\Services\TraductionService
        arguments: [@doctrine.orm.entity_manager]

    traduiresoustitreservice:
        class: Dev\SousTitreBundle\Services\TraduireSoustitreService
        # arguments: [@doctrine.orm.entity_manager, @traductionservice]
        arguments: ["@doctrine.orm.entity_manager", "@traductionservice"]

    fusionnersoustitreservice:
        class: Dev\SousTitreBundle\Services\FusionnerSoustitreService
        arguments: []
