<?php

namespace Dev\SousTitreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousTitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTitreRepository extends EntityRepository
{
}
